spot = Spot.find_by(name: '中尊寺')
spot.statues << Statue.where(id: [2, 9, 10, 11, 36, 37])
spot = Spot.find_by(name: '勝常寺')
spot.statues << Statue.where(id: [3, 12, 13])
spot = Spot.find_by(name: '大倉集古館')
spot.statues << Statue.where(id: 14)
spot = Spot.find_by(name: '深大寺')
spot.statues << Statue.where(id: [1])
spot = Spot.find_by(name: '高徳院')
spot.statues << Statue.where(id: [2])
spot = Spot.find_by(name: '願成就院')
spot.statues << Statue.where(id: [2, 31, 38])
spot = Spot.find_by(name: '園城寺')
spot.statues << Statue.where(id: [47, 48])
spot = Spot.find_by(name: '向源寺')
spot.statues << Statue.where(id: [17])
spot = Spot.find_by(name: '東寺')
spot.statues << Statue.where(id: [38, 41, 42, 25, 26, 27, 28, 31, 32, 33, 34, 35, 36, 37, 39, 40, 50, 51, 52])
spot = Spot.find_by(name: '六波羅蜜寺')
spot.statues << Statue.where(id: [17])
spot = Spot.find_by(name: '三十三間堂')
spot.statues << Statue.where(id: [18, 46, 53, 54])
spot = Spot.find_by(name: '法性寺')
spot.statues << Statue.where(id: [18])
spot = Spot.find_by(name: '醍醐寺')
spot.statues << Statue.where(id: [3, 12, 13, 16])
spot = Spot.find_by(name: '広隆寺')
spot.statues << Statue.where(id: [2, 15, 18, 19, 45])
spot = Spot.find_by(name: '神護寺')
spot.statues << Statue.where(id: [3, 16])
spot = Spot.find_by(name: '鞍馬寺')
spot.statues << Statue.where(id: [38, 43, 55])
spot = Spot.find_by(name: '仁和寺')
spot.statues << Statue.where(id: [2, 3, 10, 11])
spot = Spot.find_by(name: '清凉寺')
spot.statues << Statue.where(id: [1, 2])
spot = Spot.find_by(name: '三千院')
spot.statues << Statue.where(id: [2, 10, 11])
spot = Spot.find_by(name: '法界寺')
spot.statues << Statue.where(id: [2])
spot = Spot.find_by(name: '宝菩提院願徳寺')
spot.statues << Statue.where(id: [20])
spot = Spot.find_by(name: '大御堂観音寺')
spot.statues << Statue.where(id: [17])
spot = Spot.find_by(name: '平等院')
spot.statues << Statue.where(id: [2, 21])
spot = Spot.find_by(name: '蟹満寺')
spot.statues << Statue.where(id: [1])
spot = Spot.find_by(name: '浄瑠璃寺')
spot.statues << Statue.where(id: [2, 36, 37, 39, 40])
spot = Spot.find_by(name: '安祥寺')
spot.statues << Statue.where(id: [2, 3, 5, 6, 7, 8])
spot = Spot.find_by(name: '東大寺')
spot.statues << Statue.where(id: [1, 4, 12, 13, 19, 36, 37, 39, 40, 41, 42, 44, 56])
spot = Spot.find_by(name: '興福寺')
spot.statues << Statue.where(id: [15, 18, 19, 22, 29, 30, 36, 37, 39, 40, 44, 45, 47, 57, 58, 59, 60, 83])
spot = Spot.find_by(name: '元興寺')
spot.statues << Statue.where(id: [3])
spot = Spot.find_by(name: '唐招提寺')
spot.statues << Statue.where(id: [3, 4, 18, 36, 37, 39, 40, 41, 42, 61])
spot = Spot.find_by(name: '薬師寺')
spot.statues << Statue.where(id: [3, 10, 12, 13, 51, 62, 63])
spot = Spot.find_by(name: '新薬師寺')
spot.statues << Statue.where(id: [45])
spot = Spot.find_by(name: '法華寺')
spot.statues << Statue.where(id: [17, 57])
spot = Spot.find_by(name: '西大寺')
spot.statues << Statue.where(id: [64])
spot = Spot.find_by(name: 'なら仏像館')
spot.statues << Statue.where(id: [3])
spot = Spot.find_by(name: '円成寺')
spot.statues << Statue.where(id: [5])
spot = Spot.find_by(name: '法隆寺')
spot.statues << Statue.where(id: [1, 2, 3, 9, 10, 11, 12, 13, 15, 23, 24, 22, 36, 37, 38, 39, 40, 43, 57, 65, 66, 67, 68, 69, 70, 71])
spot = Spot.find_by(name: '中宮寺')
spot.statues << Statue.where(id: [15])
spot = Spot.find_by(name: '聖林寺')
spot.statues << Statue.where(id: [17])
spot = Spot.find_by(name: '安倍文殊院')
spot.statues << Statue.where(id: [22, 72, 73, 82])
spot = Spot.find_by(name: '室生寺')
spot.statues << Statue.where(id: [1, 17])
spot = Spot.find_by(name: '岡寺')
spot.statues << Statue.where(id: [74])
spot = Spot.find_by(name: '当麻寺')
spot.statues << Statue.where(id: [15])
spot = Spot.find_by(name: '吉野水分神社')
spot.statues << Statue.where(id: [75])
spot = Spot.find_by(name: '観心寺')
spot.statues << Statue.where(id: [20])
spot = Spot.find_by(name: '道明寺')
spot.statues << Statue.where(id: [17])
spot = Spot.find_by(name: '葛井寺')
spot.statues << Statue.where(id: [18])
spot = Spot.find_by(name: '獅子窟寺')
spot.statues << Statue.where(id: [3])
spot = Spot.find_by(name: '天野山金剛寺')
spot.statues << Statue.where(id: [5, 31, 32])
spot = Spot.find_by(name: '浄土寺')
spot.statues << Statue.where(id: [2, 10, 11])
spot = Spot.find_by(name: '慈尊院')
spot.statues << Statue.where(id: [15])
spot = Spot.find_by(name: '金剛峯寺')
spot.statues << Statue.where(id: [76])
spot = Spot.find_by(name: '道成寺')
spot.statues << Statue.where(id: [18, 12, 13])
spot = Spot.find_by(name: '熊野速玉大社')
spot.statues << Statue.where(id: [77, 78, 79, 80])
spot = Spot.find_by(name: '臼杵磨崖仏群')
spot.statues << Statue.where(id: [81])
