inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - node_modules/**/*
    - tmp/**/*

Rails: 
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb

# Example has too many lines
RSpec/ExampleLength:
  Enabled: false

# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

# Missing top-level class documentation comment
Style/Documentation:
  Enabled: false

# Missing frozen string literal comment
Style/FrozenStringLiteralComment:
  Enabled: false
