require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - node_modules/*
    - tmp/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Rails: 
  Enabled: true

Style/AsciiComments:
  Enabled: false

# Missing top-level class documentation comment
Style/Documentation:
  Enabled: false

# Missing frozen string literal comment
Style/FrozenStringLiteralComment:
  Enabled: false
