version: '3'
services:
  app:
    build: .
    environment:
      RAILS_ENV: production
    volumes:
      - .:/buddhagram
      - gem-data:/usr/local/bundle
      - node_modules:/buddhagram/node_modules
      - public-data:/buddhagram/public
      - tmp-data:/buddhagram/tmp
      - ./log:/buddhagram/log
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: bundle exec puma -C config/puma.rb
  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/buddhagram/public
      - tmp-data:/buddhagram/tmp
      - ./log:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  gem-data:
  node_modules:
  public-data:
  tmp-data:
